#!/bin/sh

set -eu

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

SWIFT_OUTPUT_FILE="$SCRIPT_DIR/BuildInfo.generated.swift"
VERSION_OUTPUT_FILE="$SCRIPT_DIR/Version.generated.env"

cd "$ROOT_DIR"

CURRENT_BRANCH="$(git symbolic-ref --short -q HEAD || true)"

# On feature branches, derive the version from the develop commit
# the feature branch is actually based on.
if [ "$CURRENT_BRANCH" != "develop" ] &&
    [ "$CURRENT_BRANCH" != "main" ] &&
    git show-ref --verify --quiet refs/heads/develop
    then
    VERSION_REF="$(git merge-base HEAD develop)"
    else
    VERSION_REF="HEAD"
    fi
    
    BASE_TAG="$(
    git describe \
    --tags \
    --abbrev=0 \
    --match 'v[0-9]*.[0-9]*.0' \
    "$VERSION_REF" 2>/dev/null || true
)"

if [ -z "$BASE_TAG" ]; then
echo "error: No version tag matching vX.Y.0 was found."
exit 1
fi

BASE_VERSION="${BASE_TAG#v}"
MAJOR_MINOR="${BASE_VERSION%.*}"

PATCH="$(
git rev-list \
--first-parent \
--merges \
--count \
"$BASE_TAG..$VERSION_REF"
)"

VERSION="$MAJOR_MINOR.$PATCH"

# Monotonically increases with develop's first-parent history.
BUILD_NUMBER="$(
git rev-list \
--first-parent \
--count \
"$VERSION_REF"
)"

COMMIT_SHA="$(git rev-parse --short=7 HEAD)"

cat > "$SWIFT_OUTPUT_FILE" <<EOF
// This file is automatically generated.
// Do not edit manually.

enum BuildInfo {
    static let version = "$VERSION"
    static let buildNumber = "$BUILD_NUMBER"
    static let commitSHA = "$COMMIT_SHA"
}
EOF

cat > "$VERSION_OUTPUT_FILE" <<EOF
LOOTRACK_VERSION=$VERSION
LOOTRACK_BUILD_NUMBER=$BUILD_NUMBER
EOF

echo "Generated Lootrack v$VERSION ($BUILD_NUMBER) [$COMMIT_SHA]"
