#!/bin/sh

set -eu

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
OUTPUT_FILE="$SCRIPT_DIR/BuildInfo.generated.swift"

cd "$ROOT_DIR"

CURRENT_BRANCH="$(git symbolic-ref --short -q HEAD || true)"

# On feature branches, derive the version from the develop commit
# the feature branch is actually based on.
if [ "$CURRENT_BRANCH" != "develop" ] &&
   [ "$CURRENT_BRANCH" != "main" ] &&
   git show-ref --verify --quiet refs/heads/develop
then
    VERSION_REF="$(git merge-base HEAD develop)"
else
    VERSION_REF="HEAD"
fi

BASE_TAG="$(
    git describe \
        --tags \
        --abbrev=0 \
        --match 'v[0-9]*.[0-9]*.0' \
        "$VERSION_REF" 2>/dev/null || true
)"

if [ -z "$BASE_TAG" ]; then
    echo "error: No version tag matching vX.Y.0 was found."
    exit 1
fi

BASE_VERSION="${BASE_TAG#v}"
MAJOR_MINOR="${BASE_VERSION%.*}"

PATCH="$(
    git rev-list \
        --first-parent \
        --merges \
        --count \
        "$BASE_TAG..$VERSION_REF"
)"

VERSION="$MAJOR_MINOR.$PATCH"
COMMIT_SHA="$(git rev-parse --short=7 HEAD)"

cat > "$OUTPUT_FILE" <<EOF
// This file is automatically generated.
// Do not edit manually.

enum BuildInfo {
    static let version = "$VERSION"
    static let commitSHA = "$COMMIT_SHA"
}
EOF

echo "Generated Lootrack v$VERSION ($COMMIT_SHA)"
